// TF-DEV: logs.html 전용 — 추천 과정(03-A) 화면.
const TF_LEGACY_LOG_LABEL_EN={'조건 정리':'Organize conditions','후보 수집':'Collect candidates','후보 검증':'Verify candidates','예산 배분':'Allocate budget','리뷰 관측':'Review observations','설명 생성':'Generate explanation','예산':'Budget','가격':'Price','성능':'Performance','파워':'Power','전원':'Power','호환성':'Compatibility','밸런스':'Balance','호환여유':'Compatibility headroom','리뷰 진위 (담당 팀원)':'Review authenticity','RAG 근거 (담당 팀원)':'RAG evidence'};
function tfLegacyLogText(text){let value=String(text||'');for(const [ko,en] of Object.entries(TF_LEGACY_LOG_LABEL_EN)){if(value===ko)value=en;else if(value.startsWith(ko+' '))value=en+value.slice(ko.length)}value=value.replace(/^(카테고리) (computer|baby), 예산 (.+)$/,(all,_word,category,budget)=>'Category: '+(category==='computer'?'Computer':'Baby care')+', budget: '+budget.replace(/원$/,'').replace(/^₩?/,'₩')).replace(/^세트 (\d+)개 부품$/,'$1 parts in the set').replace(/(\d+)\/(\d+) 슬롯$/,'$1/$2 slots').replace(/리뷰 ([\d,]+)건 중 ([\d,]+)건\(([\d.]+)%\)이 7일 안에 몰림 — 전체 상품 중앙값 ([\d.]+)%/g,'$2 of $1 reviews ($3%) were posted within 7 days — all-product median: $4%').replace(/리뷰어 ([\d,]+)명이 다른 상품에서도 함께 나타남 \(연결 상품 ([\d,]+)개\) — 중앙값 ([\d,]+)명 \/ ([\d,]+)개/g,'$1 reviewers also appeared on other products ($2 linked products) — median: $3 reviewers / $4 products').replace(/5점 비율 ([\d.]+)% — 중앙값 ([\d.]+)%/g,'5-star share: $1% — median: $2%').replace(/리뷰 ([\d,]+)건 중 ([\d,]+)건\(([\d.]+)%\)이 의심 지표 2개 이상에 걸림 \(데모 상품 전체 ([\d.]+)%\) — 95% 신뢰구간 \[([\d.]+), ([\d.]+)\]/g,'$2 of $1 reviews ($3%) triggered at least two suspicion indicators (all demo products: $4%) — 95% confidence interval [$5, $6]').replace(/기준선과 구별되지 않음/g,'not distinguishable from baseline').replace(/기준선 초과/g,'above baseline').replace(/출시 첫 주 — 조작이 아니라 출시일 수 있어 랭킹 신호에서 뺐다/g,'launch week — excluded from ranking signals because the burst may reflect the launch');for(const [ko,en] of Object.entries(TF_SLOT_LABEL_EN)){value=value.replace(new RegExp('(^| · )'+ko.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?= | · |$)','g'),'$1'+en)}return value}
function tfLocalizedLogEntries(entries){if(!tfIsEnglish())return entries;return entries.filter(entry=>{if(!['리뷰 관측','Review observations'].includes(entry.step))return true;const parts=String(entry.detail||'').split(' · ').filter(Boolean);return !(parts.length&&parts.every(part=>part.includes('No review observations')))}).map(entry=>({step:tfLegacyLogText(entry.step),title:tfLegacyLogText(entry.title),detail:tfLegacyLogText(entry.detail)}))}
function tfVerificationLog(verification,english){if(!verification||verification.status==='not_run')return '';const summary=english?'Build verification':'조합 검증';let body;if(verification.status==='ready'){body=(verification.issues||[]).map(issue=>'<div class="review"><strong>'+esc(english?tfLegacyLogText(issue.axis):issue.axis)+(issue.severity?' · '+esc(issue.severity):'')+'</strong><p>'+esc(english?tfLegacyLogText(issue.text):issue.text)+'</p></div>').join('')||'<p class="muted">'+(english?'No verification issues were found.':'확인된 쟁점이 없어요.')+'</p>'}else{body='<p class="muted">'+esc(tfLlmText(verification,english?'Generating verification details…':'검증 문장을 만드는 중이에요…',english?'Could not generate verification details.':'검증 문장을 만들지 못했어요.'))+'</p>'}return '<details open><summary>'+summary+'</summary>'+body+'</details>'}
function logsPage(){if(!tfPlan.listId)return go('category');const result=tfPlan.result;if(!result||result.list_id!==tfPlan.listId)return tfLoadResult(logsPage,2);if(result.status==='none')return go('results');const english=tfIsEnglish(),log=tfLocalizedLogEntries(result.reasoning_log||[]),verification=result.verification;shell(heading('03-A / DECISION TRACE','추천 과정을 한눈에.','추천 엔진이 단계별로 남긴 기록입니다.')+'<div class="row" style="margin-bottom:20px">'+btn(english?'← Recommendation results':'← 추천 결과','results')+'<button class="btn" type="button" data-plan-rerun="alternative">'+(english?'Search other candidates':'다른 후보 재탐색')+'</button></div><div class="panel">'+(log.length?'<div class="timeline">'+log.map(entry=>'<div><span class="tag">'+esc(entry.step)+'</span><strong>'+esc(entry.title)+'</strong><p>'+esc(entry.detail)+'</p></div>').join('')+'</div>':'<p class="muted">'+(result.status==='running'?(english?'Preparing recommendations…':'추천을 준비하는 중이에요…'):(english?'No steps have been recorded.':'기록된 단계가 없어요.'))+'</p>')+tfVerificationLog(verification,english)+'</div>',2);tfSchedulePoll(logsPage)}
async function tfStartRecommend(button,strategy){if(tfPlan.busy)return;const listId=tfPlan.listId;tfPlan.busy=true;tfBusy(button,true,'다시 계산하는 중…');try{await TF_PLAN.recommend(listId,strategy);if(listId!==tfPlan.listId)return;tfPlan.result=null;tfPlan.resultMessages=[];go('results')}catch(err){tfBusy(button,false);if(tfListGone(err))return;toast(tfAuthErrorMessage(err))}finally{tfPlan.busy=false}}
logsPage();
flow.addEventListener('click',e=>{const rerun=e.target.closest('[data-plan-rerun]');if(rerun)tfStartRecommend(rerun,rerun.dataset.planRerun||undefined)});
